services:
  - type: web
    name: peblo-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /health/ready
    plan: free
    dockerCommand: /app/start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: STORAGE_DIR
        value: /app/storage
      - key: CATALOG_PATH
        value: /app/storage/catalogue.json
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://peblo-cms.onrender.com,https://peblo-viewer.onrender.com
      - key: EDITOR_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false

  - type: web
    name: peblo-cms
    runtime: docker
    dockerfilePath: ./cms/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: VITE_API_BASE
        value: https://peblo-api-l2mv.onrender.com
      - key: API_BASE_URL
        value: https://peblo-api-l2mv.onrender.com

  - type: web
    name: peblo-viewer
    runtime: docker
    dockerfilePath: ./viewer/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: VITE_API_BASE
        value: https://peblo-api.onrender.com
      - key: API_BASE_URL
        value: https://peblo-api.onrender.com
