import { FormEvent, useEffect, useState } from 'react'
import { getToken, imageUrl, request, setToken, type Episode, type Report, type Run, type Season, type Show } from './api'

const sections = ['featured', 'series', 'minisodes', 'songs']
const categories = ['adventure', 'folk', 'friendship', 'india', 'language', 'learning', 'maths', 'music', 'nature', 'reading', 'science', 'singalong', 'stories', 'travel', 'values']

function Button({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button className="button" {...props}>{children}</button> }

function Login({ onLogin }: { onLogin: () => void }) {
  const [value, setValue] = useState(''); const [error, setError] = useState('')
  const enter = (token: string) => { setToken(token); request('/health').then(onLogin).catch(() => setError('The API is not running yet. Start the backend or Docker Compose.')) }
  return <main className="login"><div className="login-card"><div className="mark">P</div><p className="eyebrow">PEBLO TV / STUDIO</p><h1>Make something<br/><em>wonderful.</em></h1><p className="muted">A calm little workspace for your next adventure.</p><form onSubmit={e => { e.preventDefault(); if (value.trim()) enter(value.trim()) }}><label>Access token<input value={value} onChange={e => setValue(e.target.value)} placeholder="Paste bearer token" type="password"/></label>{error && <p className="error">{error}</p>}<Button type="submit">Enter studio <span>→</span></Button></form><div className="demo-access"><small>Local demo access</small><div><button type="button" className="text-button" onClick={() => enter('peblo-editor-token')}>Editor token</button><button type="button" className="text-button" onClick={() => enter('peblo-admin-token')}>Admin token</button></div></div><small>Editors manage content. Admins can publish.</small></div></main>
}

function ArtworkSlot({ kind, episode, onUpload }: { kind: string; episode?: Episode; onUpload?: (kind: string, file: File) => Promise<void> }) {
  const [preview, setPreview] = useState<string>(); const [error, setError] = useState('')
  const specs: Record<string, string> = { poster: '600 × 900 px · 2:3', banner: '1280 × 720 px · 16:9', thumbnail: '640 × 360 px · 16:9' }
  const existing = episode?.artwork.find(a => a.kind === kind)?.url
  return <label className="art-slot"><div className="art-head"><strong>{kind[0].toUpperCase() + kind.slice(1)}</strong><small>{specs[kind]}</small></div><div className={`art-preview ${kind}`}>{preview || existing ? <img src={preview || imageUrl(existing!)} /> : <span>＋</span>}</div><input type="file" accept="image/jpeg,image/png" disabled={!onUpload} onChange={async e => { const file = e.target.files?.[0]; if (!file || !onUpload) return; setError(''); setPreview(URL.createObjectURL(file)); try { await onUpload(kind, file) } catch (err) { setError((err as Error).message); setPreview(undefined) } }}/><small className="upload-hint">{onUpload ? 'Upload image · max 200 KB' : 'Add an episode first'}</small>{error && <span className="error">{error}</span>}</label>
}

function EpisodeManager({ showId }: { showId: number }) {
  const [seasons, setSeasons] = useState<Season[]>([]); const [season, setSeason] = useState<Season>(); const [episode, setEpisode] = useState<Episode>(); const [title, setTitle] = useState(''); const [seasonTitle, setSeasonTitle] = useState('Main season'); const [loading, setLoading] = useState(true)
  const loadSeason = async (item: Season, clearEpisode = true) => { setSeason(await request<Season>(`/admin/seasons/${item.id}`)); if (clearEpisode) setEpisode(undefined) }
  const load = async () => { setLoading(true); try { const result = await request<{ items: Season[] }>(`/admin/shows/${showId}/seasons`); setSeasons(result.items); if (result.items.length) await loadSeason(result.items[0]) } catch (e) { alert((e as Error).message) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [showId])
  const createSeason = async () => { try { const created = await request<Season>(`/admin/shows/${showId}/seasons`, { method: 'POST', body: JSON.stringify({ number: Math.max(0, ...seasons.map(s => s.number)) + 1, title: seasonTitle }) }); setSeasons([...seasons, created]); await loadSeason(created) } catch (e) { alert((e as Error).message) } }
  const save = async () => { if (!season || !title.trim()) return; try { const ep = await request<Episode>(`/admin/seasons/${season.id}/episodes`, { method: 'POST', body: JSON.stringify({ number: (season.episodes?.length ?? 0) + 1, title: title.trim(), duration_seconds: 300, language: 'en', content_group: `${showId}-${Date.now()}`, status: 'draft' }) }); setEpisode(ep); setTitle(''); await loadSeason(season, false) } catch (e) { alert((e as Error).message) } }
  const upload = async (kind: string, file: File) => { if (!episode) return; const data = new FormData(); data.append('file', file); await request(`/admin/episodes/${episode.id}/artwork/${kind}`, { method: 'POST', body: data }); setEpisode(await request<Episode>(`/admin/episodes/${episode.id}`)); await loadSeason(season!, false) }
  if (loading) return <div className="state">Loading episode lists…</div>
  return <div className="episodes"><div className="subhead"><div><p className="eyebrow">EPISODES</p><h3>{season ? `Season ${season.number}` : 'Start the episode list'}</h3></div>{season && <span className="pill">{season.episodes?.length ?? 0} episodes</span>}</div>{seasons.length > 0 && <label>Season<select value={season?.id ?? ''} onChange={e => { const found = seasons.find(s => s.id === Number(e.target.value)); if (found) void loadSeason(found) }}>{seasons.map(s => <option key={s.id} value={s.id}>Season {s.number}: {s.title || 'Untitled'}</option>)}</select></label>}{!season && <div className="quick-add"><input value={seasonTitle} onChange={e => setSeasonTitle(e.target.value)} placeholder="Season title"/><Button type="button" onClick={createSeason}>Create season</Button></div>}{season?.episodes?.map(e => <div className="episode-line" key={e.id}><span className="episode-num">{String(e.number).padStart(2, '0')}</span><div><strong>{e.title}</strong><small>{e.language.toUpperCase()} · {e.duration_seconds ? `${Math.round(e.duration_seconds / 60)} min` : 'No duration'}</small></div><span className={`status ${e.status}`}>{e.status}</span><button className="text-button" onClick={() => setEpisode(e)}>Artwork</button></div>)}{season && <div className="quick-add"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="New episode title"/><Button type="button" onClick={save} disabled={!title.trim()}>Add episode</Button></div>}{episode && <div className="artwork-grid">{['poster', 'banner', 'thumbnail'].map(k => <ArtworkSlot key={k} kind={k} episode={episode} onUpload={upload}/>)}</div>}</div>
}

function ShowEditor({ show, onSaved, onCancel }: { show?: Show; onSaved: () => void; onCancel: () => void }) {
  const [form, setForm] = useState({ title: show?.title ?? '', slug: show?.slug ?? '', synopsis: show?.synopsis ?? '', section: show?.section ?? '', status: show?.status ?? 'draft', categories: show?.categories ?? [] as string[] }); const [saving, setSaving] = useState(false)
  const update = (key: string, value: string) => setForm({ ...form, [key]: value })
  const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); try { await request(`/admin/shows${show ? `/${show.id}` : ''}`, { method: show ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, section: form.section || null }) }); onSaved() } catch (err) { alert((err as Error).message) } finally { setSaving(false) } }
  return <section className="panel editor"><div className="panel-title"><div><p className="eyebrow">{show ? 'EDIT SHOW' : 'NEW SHOW'}</p><h2>{show?.title ?? 'Create a show'}</h2></div><button className="text-button" onClick={onCancel}>Close ×</button></div><form onSubmit={submit} className="form-grid"><label>Show title<input required value={form.title} onChange={e => update('title', e.target.value)} placeholder="e.g. The Little Explorers"/></label><label>Slug<input required value={form.slug} onChange={e => update('slug', e.target.value)} placeholder="little-explorers"/></label><label className="wide">Synopsis<textarea value={form.synopsis} onChange={e => update('synopsis', e.target.value)} rows={3}/></label><label>Section<select value={form.section} onChange={e => update('section', e.target.value)}><option value="">Choose a section</option>{sections.map(x => <option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e => update('status', e.target.value)}><option>draft</option><option>published</option></select></label><div className="wide"><span className="field-label">Categories</span><div className="chips">{categories.map(c => <button type="button" className={form.categories.includes(c) ? 'chip selected' : 'chip'} key={c} onClick={() => setForm({ ...form, categories: form.categories.includes(c) ? form.categories.filter(x => x !== c) : [...form.categories, c] })}>{c}</button>)}</div></div><div className="wide editor-actions"><Button type="submit" disabled={saving}>{saving ? 'Saving…' : show ? 'Save changes' : 'Create show'}</Button><button type="button" className="text-button" onClick={onCancel}>Cancel</button></div></form>{show && <EpisodeManager showId={show.id}/>}</section>
}

function Publish({ report, runs, onPublished }: { report?: Report; runs: Run[]; onPublished: () => void }) { const [busy, setBusy] = useState(false); const issues = Object.values(report?.issues ?? {}).flat(); const blocked = report?.blocking === true; return <div className="publish-grid"><section className="panel release-card"><div className="release-icon">✦</div><p className="eyebrow">CATALOGUE STATUS</p><h2>{blocked ? 'A few things need care' : 'Your catalogue is ready'}</h2><p className="muted">{blocked ? 'Resolve these checks before your shows can go live.' : 'Everything looks good. Publishing makes the latest approved content visible to families.'}</p>{blocked && <div className="issues">{issues.map((x, i) => <div className="issue" key={i}><span>!</span><div><strong>{x.message ?? 'Content needs attention'}</strong><small>Check the show or episode details</small></div></div>)}</div>}<Button disabled={blocked || busy} onClick={async () => { setBusy(true); try { await request('/admin/catalog/publish', { method: 'POST' }); onPublished() } catch (e) { alert((e as Error).message) } finally { setBusy(false) } }}>{busy ? 'Publishing…' : 'Publish catalogue →'}</Button></section><section className="panel history"><div className="panel-title"><div><p className="eyebrow">HISTORY</p><h3>Release history</h3></div><span className="pill">{runs.length} runs</span></div>{runs.length === 0 ? <div className="state">No releases yet.</div> : runs.map(r => <div className="run" key={r.id}><span className={`run-dot ${r.outcome}`}></span><div><strong>Release #{r.id}</strong><small>{r.actor} · {new Date(r.started_at).toLocaleString()}</small></div><span className={r.outcome === 'success' ? 'success-text' : 'error'}>{r.outcome}</span></div>)}</section></div> }

function Content({ onLogout }: { onLogout: () => void }) {
  const [tab, setTab] = useState<'shows' | 'publish'>('shows'); const [shows, setShows] = useState<Show[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [q, setQ] = useState(''); const [status, setStatus] = useState(''); const [section, setSection] = useState(''); const [language, setLanguage] = useState(''); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Show | null>(); const [report, setReport] = useState<Report>(); const [runs, setRuns] = useState<Run[]>([])
  const refresh = () => { setLoading(true); setError(''); request<{ items: Show[] }>(`/admin/shows?q=${encodeURIComponent(q)}&status=${status}&section=${section}&language=${language}`).then(x => setShows(x.items)).catch(e => setError((e as Error).message)).finally(() => setLoading(false)) }
  useEffect(() => { refresh() }, [q, status, section, language]); useEffect(() => { if (tab === 'publish') { request<Report>('/admin/validation-report').then(setReport).catch(e => setError((e as Error).message)); request<{ items: Run[] }>('/admin/catalog/runs').then(x => setRuns(x.items)).catch(() => {}) } }, [tab])
  const visible = shows.slice((page - 1) * 8, page * 8)
  return <div className="app-shell"><aside><div className="brand"><div className="mark small">P</div><span>peblo <b>tv</b></span></div><div className="workspace"><span className="avatar">E</span><div><strong>Editorial team</strong><small>Studio workspace</small></div></div><nav><button className={tab === 'shows' ? 'active' : ''} onClick={() => setTab('shows')}>▦ <span>Shows</span></button><button className={tab === 'publish' ? 'active' : ''} onClick={() => setTab('publish')}>◈ <span>Publish</span></button></nav><div className="aside-bottom"><small>PEBLO TV MINI</small><button onClick={onLogout}>↪ Sign out</button></div></aside><main className="main"><header><div><p className="eyebrow">{tab === 'shows' ? 'CONTENT LIBRARY' : 'RELEASE DESK'}</p><h1>{tab === 'shows' ? 'Your shows' : 'Ready for launch?'}</h1></div>{tab === 'shows' && <Button onClick={() => setEditing(null)}>＋ New show</Button>}</header>{tab === 'publish' ? <Publish report={report} runs={runs} onPublished={() => setTab('shows')}/> : editing !== undefined ? <ShowEditor show={editing || undefined} onSaved={() => { setEditing(undefined); refresh() }} onCancel={() => setEditing(undefined)}/> : <><div className="toolbar"><input value={q} onChange={e => { setQ(e.target.value); setPage(1) }} placeholder="Search shows…"/><select value={section} onChange={e => setSection(e.target.value)}><option value="">All sections</option>{sections.map(x => <option key={x}>{x}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option>draft</option><option>published</option></select><select value={language} onChange={e => setLanguage(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option></select></div>{error && <p className="error">{error}</p>}{loading ? <div className="state">Loading shows…</div> : visible.length === 0 ? <div className="state">No shows found. Start your next adventure with <button className="text-button" onClick={() => setEditing(null)}>New show</button>.</div> : <div className="show-grid">{visible.map(show => <button className="show-card" key={show.id} onClick={() => setEditing(show)}><span className="show-art">{show.title[0]}</span><span className="show-name"><strong>{show.title}</strong><small>{show.section ?? 'Unassigned'} · {show.status}</small></span></button>)}</div>}</>}</main></div>
}

export function App() { const [token, setLocalToken] = useState(getToken()); return token ? <Content onLogout={() => { localStorage.removeItem('peblo-token'); setToken(''); setLocalToken('') }}/> : <Login onLogin={() => setLocalToken(getToken())}/> }
