import { useEffect, useState } from 'react'
import { getCatalog, imageUrl, searchCatalog, type Catalog, type Episode, type Show } from './api'
const categories=['adventure','folk','friendship','india','language','learning','maths','music','nature','reading','science','singalong','stories','travel','values']
function Placeholder({wide=false}:{wide?:boolean}){return <div className={`placeholder ${wide?'wide-placeholder':''}`} />}
function Art({url,alt,wide=false}:{url?:string;alt:string;wide?:boolean}){const[loaded,setLoaded]=useState(false);return <div className={`art ${wide?'wide-art':''}`}>{!loaded&&<Placeholder wide={wide}/>} {url&&<img src={imageUrl(url)} alt={alt} onLoad={()=>setLoaded(true)} onError={()=>setLoaded(true)} style={{opacity:loaded?1:0}}/>}</div>}
function Card({show,onOpen}:{show:Show;onOpen:(show:Show)=>void}){const art=show.seasons.flatMap(s=>s.episodes).find(e=>e.artwork.poster)?.artwork.poster;return <button className="card" onClick={()=>onOpen(show)}><Art url={art} alt=""/><span>{show.title}</span><small>{show.categories.slice(0,2).join(' · ')}</small></button>}
function ShowDetail({show,onBack}:{show:Show;onBack:()=>void}){const seasons=show.seasons.filter(s=>s.number!==0);const first=seasons[0];const hero=first?.episodes[0];return <main className="detail"><button className="back" onClick={onBack}>← Back to browse</button><div className="detail-top"><div className="detail-copy"><p className="kicker">{show.categories.join('  ·  ')}</p><h1>{show.title}</h1><p>{show.synopsis||'A new adventure is waiting.'}</p><div className="detail-meta"><span>✦ {seasons.length} seasons</span><span>◉ All ages</span></div></div>{hero&&<Art wide url={hero.artwork.banner||hero.artwork.thumbnail} alt=""/>}</div><div className="detail-content"><h2>Episodes</h2>{seasons.length===0?<p className="empty">Episodes are on their way.</p>:seasons.map(season=><section className="season" key={season.number}><h3>Season {season.number} <small>{season.title}</small></h3><div className="episode-grid">{season.episodes.map((ep,i)=><EpisodeCard key={`${ep.title}-${i}`} episode={ep}/>)}</div></section>)}</div></main>}
function EpisodeCard({episode}:{episode:Episode}){return <article className="episode-card"><Art url={episode.artwork.thumbnail} alt=""/><div className="episode-info"><span className="episode-no">EP {String(episode.episode_number).padStart(2,'0')}</span><h4>{episode.title}</h4><p>{episode.duration_seconds?`${Math.floor(episode.duration_seconds/60)} min`:'Short story'}</p><div className="languages">{episode.languages.map(l=><span key={l}>{l==='en'?'English':'हिन्दी'}</span>)}</div></div></article>}
function App(){const[catalog,setCatalog]=useState<Catalog>();const[error,setError]=useState('');const[q,setQ]=useState('');const[category,setCategory]=useState('');const[language,setLanguage]=useState('');const[selected,setSelected]=useState<Show>();const[results,setResults]=useState<Show[]|null>(null);const[menu,setMenu]=useState(false);useEffect(()=>{getCatalog().then(setCatalog).catch(e=>setError(e.message))},[]);useEffect(()=>{if(!q&&!category&&!language){setResults(null);return}const timer=setTimeout(()=>searchCatalog(q,category,language).then(setResults).catch(e=>setError(e.message)),260);return()=>clearTimeout(timer)},[q,category,language]);if(selected)return <><Header q={q} setQ={setQ} menu={menu} setMenu={setMenu}/><ShowDetail show={selected} onBack={()=>setSelected(undefined)}/></>;const sections=results?[{name:'Search results',shows:results}]:catalog?.sections??[];const featured=catalog?.sections.flatMap(s=>s.shows)[0];return <><Header q={q} setQ={setQ} menu={menu} setMenu={setMenu}/>{error?<div className="full-state"><h2>We hit a little bump</h2><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div>:!catalog?<div className="loading-home"><Placeholder wide/><Placeholder/><Placeholder/></div>:<main><section className="hero"><Art wide url={featured?.seasons[0]?.episodes[0]?.artwork.banner} alt=""/><div className="hero-copy"><p className="kicker">PEBLO ORIGINAL · {featured?.categories[0]??'NEW STORIES'}</p><h1>{featured?.title??'Big little adventures'}</h1><p>{featured?.synopsis??'Stories made for curious minds and the grown-ups who watch with them.'}</p><button onClick={()=>featured&&setSelected(featured)}>Explore show <span>→</span></button></div></section><section className="filters"><div className="filter-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="What do you want to explore?"/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Every category</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="hi">हिन्दी</option></select></section><div className="rows">{sections.map(section=><section className="row" key={section.name}><div className="row-title"><h2>{section.name}</h2><span>{section.shows.length} shows</span></div><div className="cards">{section.shows.map(s=><Card key={s.slug} show={s} onOpen={setSelected}/>)}</div></section>)}{sections.every(s=>!s.shows.length)&&<div className="full-state"><h2>Nothing here yet</h2><p>Try a different adventure, category, or language.</p></div>}</div></main>}</>}
function Header({q,setQ,menu,setMenu}:{q:string;setQ:(x:string)=>void;menu:boolean;setMenu:(x:boolean)=>void}){return <header className="site-header"><a className="logo" href="/">peblo<span>tv</span></a><nav className={menu?'open':''}><a href="#browse">Browse</a><a href="#new">New this week</a></nav><div className="header-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search"/></div><button className="menu" onClick={()=>setMenu(!menu)}>☰</button><div className="profile">P</div></header>}
export { App }
